### ISSUE TITLE
[Meta] Milestone 1

### ISSUE THREAD

**Issue by mjakeman** [se306-2022/project-2-team-1#36]
Checklist for completing Milestone 1

- [X] Write the report
- [x] Fix graphviz parser
- [x] Properly get source nodes using API
- [x] Update the README
    - [x] Mention the three module structure
    - [x] Describe each module and what it does
    - [x] Describe how to run CLI and GUI
    - [x] Describe command line options for CLI
    - [x] Building the JAR
    - [x] Running the JAR
- [x] Brief documentation of overall architecture
- [x] Get numProcessors from CLI
- [x] Account for multiple root nodes
- [x] Comment classes fully
    - [x] scheduler-cli @JJTee 
    - [x] scheduler-gui @mjakeman 
    - [x] scheduler-core graph @nset793 
    - [x] scheduler-core algorithm @bliu631 
    - [x] scheduler-core matrix @jsan956-ai 
- [x] Some refactoring for code quality purposes
- [x] Integrate test suite
- [x] Submit JAR
